
-- TABLA OPERADOR

CREATE TABLE OPERADOR (
    operador_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    nombre_operador VARCHAR2(100) NOT NULL
);

-- TABLA EQUIPO

CREATE TABLE EQUIPO (
    equipo_id VARCHAR2(10) PRIMARY KEY
);

-- TABLA REGISTRO_PRODUCCION

CREATE TABLE REGISTRO_PRODUCCION (
    registro_id NUMBER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    turno VARCHAR2(10),
    zona VARCHAR2(20),
    toneladas_extraidas NUMBER(10,2),
    horas_operativas NUMBER(5,2),
    consumo_combustible NUMBER(10,2),
    incidentes NUMBER,
    ley_mineral NUMBER(5,2),

    operador_id NUMBER,
    equipo_id VARCHAR2(10),

    CONSTRAINT fk_operador
        FOREIGN KEY (operador_id)
        REFERENCES OPERADOR (operador_id),

    CONSTRAINT fk_equipo
        FOREIGN KEY (equipo_id)
        REFERENCES EQUIPO (equipo_id)
);

SELECT table_name
FROM user_tables
WHERE table_name IN ('OPERADOR', 'EQUIPO', 'REGISTRO_PRODUCCION');




